<table>
    <thead>
    <tr>
    <th>cnic</th>
    <th>username</th>
    <th>password</th>
    </tr>
    </thead>
    <tbody>
        @if($data!=null)
            @foreach($data as $vl)
            <tr>
                <td>{{$vl['cnic']}}</td>
                <td>{{$vl['username']}}</td>
                <td>{{$vl['password']}}</td>
            </tr>
            @endforeach
        @endif
    </tbody>
</table>